/**
 * Resolving the version a repository actually has.
 *
 * The case that matters is the ordinary one: a manifest says `^2.1.3` and the run needs to
 * know that this resolved to `2.1.3`, because every question research asks is about two
 * concrete versions. Fixtures that pin exactly hid this for a long time, and real repositories
 * almost never pin.
 *
 * The lockfile content below is taken from files the three managers actually wrote, rather
 * than invented, because the details that break a parser — quoting, peer suffixes, the
 * difference between `importers` and `packages` — are details no one would invent correctly.
 */

import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  isExactVersion,
  lockfilePackageVersions,
  resolveInstalledVersion,
  unexpectedLockfileMoves,
} from "@safe-upgrade/bootstrap";
import type { PackageManager } from "@safe-upgrade/domain";

function resolve(
  manager: PackageManager,
  filename: string,
  content: string,
  packageName: string,
  workspace = "",
) {
  const directory = mkdtempSync(join(tmpdir(), "lock-"));
  const path = join(directory, filename);
  writeFileSync(path, content);
  return resolveInstalledVersion(manager, path, packageName, workspace);
}

const NPM_V3 = JSON.stringify({
  name: "probe",
  lockfileVersion: 3,
  packages: {
    "": { name: "probe", dependencies: { ms: "^2.1.3" } },
    "node_modules/@babel/code-frame": { version: "7.29.7" },
    "node_modules/ms": {
      version: "2.1.3",
      resolved: "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz",
    },
  },
});

const NPM_V1 = JSON.stringify({
  name: "probe",
  lockfileVersion: 1,
  dependencies: { ms: { version: "2.1.3", resolved: "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz" } },
});

const PNPM = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true

importers:

  .:
    dependencies:
      '@babel/code-frame':
        specifier: ^7.24.0
        version: 7.29.7
      ms:
        specifier: ^2.1.3
        version: 2.1.3
    devDependencies:
      escape-string-regexp:
        specifier: ~4.0.0
        version: 4.0.0

  packages/child:
    dependencies:
      ms:
        specifier: ^2.0.0
        version: 2.0.0

packages:

  ms@2.1.3:
    resolution: {integrity: sha512-xyz}
`;

const YARN_CLASSIC = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.24.0":
  version "7.29.7"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.29.7.tgz#abc"

escape-string-regexp@~4.0.0:
  version "4.0.0"
  resolved "https://registry.yarnpkg.com/escape-string-regexp/-/escape-string-regexp-4.0.0.tgz#def"

ms@^2.1.3:
  version "2.1.3"
  resolved "https://registry.yarnpkg.com/ms/-/ms-2.1.3.tgz#ghi"
`;

const YARN_BERRY = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10c0

"ms@npm:^2.1.3":
  version: 2.1.3
  resolution: "ms@npm:2.1.3"
  checksum: 10c0/abc
  languageName: node
  linkType: hard

"probe@workspace:.":
  version: 0.0.0-use.local
  resolution: "probe@workspace:."
`;

describe("npm", () => {
  it("reads the root copy of a direct dependency", () => {
    expect(resolve("npm", "package-lock.json", NPM_V3, "ms")).toBe("2.1.3");
  });

  it("keeps a scoped name intact", () => {
    expect(resolve("npm", "package-lock.json", NPM_V3, "@babel/code-frame")).toBe("7.29.7");
  });

  it("still reads the old layout", () => {
    expect(resolve("npm", "package-lock.json", NPM_V1, "ms")).toBe("2.1.3");
  });

  it("ignores a nested copy belonging to some other dependent", () => {
    // `node_modules/other/node_modules/ms` is a different copy for a different dependent, and
    // reporting it as this repository's version would compare the wrong pair of versions.
    const nested = JSON.stringify({
      lockfileVersion: 3,
      packages: { "node_modules/other/node_modules/ms": { version: "1.0.0" } },
    });
    expect(resolve("npm", "package-lock.json", nested, "ms")).toBeNull();
  });

  it("answers nothing for a package that is not there", () => {
    expect(resolve("npm", "package-lock.json", NPM_V3, "lodash")).toBeNull();
  });

  it("answers nothing for a file that is not json", () => {
    expect(resolve("npm", "package-lock.json", "{ not json", "ms")).toBeNull();
  });
});

describe("pnpm", () => {
  it("reads the root project's resolution", () => {
    expect(resolve("pnpm", "pnpm-lock.yaml", PNPM, "ms")).toBe("2.1.3");
  });

  it("does not take a workspace member's resolution for the root's", () => {
    // `packages/child` resolved ms to 2.0.0. Reading the first match in the file would have
    // returned whichever project came first.
    expect(resolve("pnpm", "pnpm-lock.yaml", PNPM, "ms")).not.toBe("2.0.0");
  });

  it("handles a quoted scoped key", () => {
    expect(resolve("pnpm", "pnpm-lock.yaml", PNPM, "@babel/code-frame")).toBe("7.29.7");
  });

  it("reads dev dependencies too", () => {
    expect(resolve("pnpm", "pnpm-lock.yaml", PNPM, "escape-string-regexp")).toBe("4.0.0");
  });

  it("strips the peers a version was resolved against", () => {
    const peers = PNPM.replace("version: 2.1.3", "version: 2.1.3(@langchain/core@1.2.11)(zod@3.0.0)");
    expect(resolve("pnpm", "pnpm-lock.yaml", peers, "ms")).toBe("2.1.3");
  });

  it("treats a workspace link as no published version at all", () => {
    const linked = PNPM.replace("version: 2.1.3", "version: link:../ms");
    expect(resolve("pnpm", "pnpm-lock.yaml", linked, "ms")).toBeNull();
  });

  it("reads the workspace importer when one is named", () => {
    expect(resolve("pnpm", "pnpm-lock.yaml", PNPM, "ms", "packages/child")).toBe("2.0.0");
  });

  it("does not read the store listing as a resolution", () => {
    // `packages:` lists every version in the store, including several of one package. Only
    // `importers` says what this project chose.
    const storeOnly = `lockfileVersion: '9.0'\n\npackages:\n\n  ms@9.9.9:\n    resolution: {integrity: sha512-x}\n`;
    expect(resolve("pnpm", "pnpm-lock.yaml", storeOnly, "ms")).toBeNull();
  });
});

describe("yarn", () => {
  it("reads a classic lockfile", () => {
    expect(resolve("yarn", "yarn.lock", YARN_CLASSIC, "ms")).toBe("2.1.3");
  });

  it("reads a berry lockfile", () => {
    expect(resolve("yarn", "yarn.lock", YARN_BERRY, "ms")).toBe("2.1.3");
  });

  it("keeps a scoped name intact in a quoted descriptor", () => {
    expect(resolve("yarn", "yarn.lock", YARN_CLASSIC, "@babel/code-frame")).toBe("7.29.7");
  });

  it("does not match a package whose name merely ends with the one asked for", () => {
    // `escape-string-regexp` must not answer for `string-regexp`.
    expect(resolve("yarn", "yarn.lock", YARN_CLASSIC, "string-regexp")).toBeNull();
  });

  it("refuses to choose when dependents disagree", () => {
    // Two blocks, two versions, and nothing in the file says which one the root project got.
    // A guess here would silently research the wrong version.
    const conflicting = `${YARN_CLASSIC}\nms@^2.0.0:\n  version "2.0.0"\n  resolved "https://registry.yarnpkg.com/ms/-/ms-2.0.0.tgz#jkl"\n`;
    expect(resolve("yarn", "yarn.lock", conflicting, "ms")).toBeNull();
  });

  it("is untroubled by one version appearing in two descriptors", () => {
    const merged = YARN_CLASSIC.replace("ms@^2.1.3:", 'ms@^2.1.3, ms@^2.1.0:');
    expect(resolve("yarn", "yarn.lock", merged, "ms")).toBe("2.1.3");
  });

  it("ignores the workspace's own entry", () => {
    expect(resolve("yarn", "yarn.lock", YARN_BERRY, "probe")).toBeNull();
  });
});

describe("a missing file", () => {
  it("is unanswered rather than an exception", () => {
    // Detection turns null into a refusal with an explanation. A throw from here would
    // surface as an internal error instead.
    expect(resolveInstalledVersion("npm", "/nonexistent/package-lock.json", "ms")).toBeNull();
  });
});

describe("unexpected lockfile moves", () => {
  it("names packages that changed and were not on the run", () => {
    const directory = mkdtempSync(join(tmpdir(), "lock-"));
    const path = join(directory, "package-lock.json");
    writeFileSync(path, NPM_V3);
    const before = lockfilePackageVersions("npm", path);
    const extra = unexpectedLockfileMoves(before, { ...before, picocolors: ["1.1.1"] }, new Set(["ms"]));
    expect(extra).toEqual(["picocolors <absent> -> 1.1.1"]);
  });
});

describe("recognising an exact version", () => {
  it("accepts what a lockfile would write", () => {
    for (const version of ["1.0.0", "0.0.1", "10.20.30", "1.0.0-rc.1", "2.0.0+build.5"]) {
      expect(isExactVersion(version), version).toBe(true);
    }
  });

  it("rejects everything that is a claim about a set of versions", () => {
    // Each of these is what a real manifest says, and none of them can be fetched, compared,
    // or classified as a major bump.
    for (const range of ["^2.1.3", "~4.0.0", ">=1.0.0", "1.x", "1.2", "latest", "*", "", "npm:ms@2"]) {
      expect(isExactVersion(range), range).toBe(false);
    }
  });
});
